version: '3.3'

services:

    mongodb:
        image: mongo:4.0.1
        environment:
            MONGO_DATA_DIR: "/data/db"
            MONGO_LOG_DIR: "/dev/null"
        volumes:
            - ./data/db:/data/db
        ports:
            - "$DB_EXPOSE_PORT:27017"
        networks:
            - backend

    writer:
        depends_on:
            - mongodb
        build:
            context: .
            dockerfile: ./Dockerfile.writer
        environment:
            LOGS_LIST: $LOGS_LIST
            LOGS_FORMAT: $LOGS_FORMAT
        volumes:
            - logs:/logs
        networks:
            - backend

    gologtail:
        depends_on:
            - mongodb
            - writer
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            DB_HOST: mongodb
            DB_PORT: 27017
            DB_NAME: $DB_NAME
            DB_TABLE: $DB_TABLE
            DB_WORKERS: $DB_WORKERS
            LOGS_LIST: $LOGS_LIST
            LOGS_FORMAT: $LOGS_FORMAT
        volumes:
            - logs:/logs
        networks:
            - backend

volumes:
    logs:

networks:
    backend:
